version: '3.7'
services:
  wordpress-develop:
    volumes:
      - ../tools/local-env/default.template:/etc/nginx/conf.d/default.template
      - ..:/var/www/${LOCAL_DIR-src}/wp-content/plugins/woocommerce-local-pickup-time-select
      - ../vendor/woocommerce/woocommerce:/var/www/${LOCAL_DIR-src}/wp-content/plugins/woocommerce

    # Load our config file, substituning environment variables into the config.
    command: /bin/sh -c "envsubst '$$LOCAL_DIR $$LOCAL_HOSTNAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  php:
    volumes:
      - ..:/var/www/${LOCAL_DIR-src}/wp-content/plugins/woocommerce-local-pickup-time-select
      - ../vendor/woocommerce/woocommerce:/var/www/${LOCAL_DIR-src}/wp-content/plugins/woocommerce
  cli:
    volumes:
      - ..:/var/www/${LOCAL_DIR-src}/wp-content/plugins/woocommerce-local-pickup-time-select
      - ../vendor/woocommerce/woocommerce:/var/www/${LOCAL_DIR-src}/wp-content/plugins/woocommerce
  phpunit:
    volumes:
      - ..:/var/www/${LOCAL_DIR-src}/wp-content/plugins/woocommerce-local-pickup-time-select
      - ../vendor/woocommerce/woocommerce:/var/www/${LOCAL_DIR-src}/wp-content/plugins/woocommerce
