name: Coding Standards

on:
  pull_request:
  push:
    branches:
      - develop
      - 'release/**'
      - 'feature/**'
      - 'fix/**'

env:
  PHP_VERSION: 7.4
  WP_MULTISITE: 0
  ACTION_VERSION: 2

jobs:
  check:
    name: Setup & Check Coding Standards

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup PHP Environment
      uses: shivammathur/setup-php@v2
      # https://github.com/marketplace/actions/setup-php-action
      with:
        php-version: ${{ env.PHP_VERSION }}
        tools: composer:v2

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      env:
        composer-cache-name: cache-composer
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.composer-cache-name }}-v${{ env.ACTION_VERSION }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.composer-cache-name }}-v${{ env.ACTION_VERSION }}-

    - name: Install Composer Dependencies
      run: composer install

    - name: Check WordPress Coding Standards
      run: composer run-script lint
