name: PR Unit Testing

on:
  pull_request:

env:
  PHP_PREF_MIN_VERSION: '7.3'
  WP_STABLE_VERSION: '5.5.*'
  WP_MULTISITE: 0
  WC_STABLE_VERSION: '4.8.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      # https://github.com/marketplace/actions/setup-php-action
      with:
        php-version: ${{ env.PHP_PREF_MIN_VERSION }}
        tools: composer:v1
    - uses: actions/setup-node@v1
      # https://github.com/marketplace/actions/setup-node-js-environment
      with:
        node-version: 12.x

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      env:
        composer-cache-name: cache-vendor
      with:
        path: ~/vendor
        key: ${{ runner.os }}-build-${{ env.composer-cache-name }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.composer-cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Require Specified WordPress Version
      run: composer require wordpress/wordpress:${{ env.WP_STABLE_VERSION }} --dev --prefer-source --update-with-all-dependencies

    - name: Require Specified WooCommerce Version
      run: composer require woocommerce/woocommerce:${{ env.WC_STABLE_VERSION }} --dev --prefer-source --update-with-all-dependencies

    - name: PHPUnit PHP 7.4 Support
      if: ${{ env.PHP_PREF_MIN_VERSION }} == '7.4'
      run: |
        composer global require phpunit/php-code-coverage=dev-master
        composer global require sebastian/global-state:dev-master
        composer global require phpunit/phpunit=dev-master

    - name: Environment Setup
      run: npm run ci:setup

    - name: Unit Tests
      run: npm run test
